spring:
  profiles:
    include:
      - mysql
      - secret
      - aws

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error