spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_RDS_ENDPOINT}:3306/${MYSQL_RDS_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: ${MYSQL_RDS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  redis:
    host: ${REDIS_PROD_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

cloud:
  aws:
    bucket: ${IMAGE_BUCKET_NAME}
    folder:
      profile: ${IMAGE_PROFILE_FILE_PATH}
      paint: ${IMAGE_PAINT_FILE_PATH}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_IMAGE_ACCESS_KEY}
      secretKey: ${AWS_IMAGE_SECRET_KEY}

coolsms:
  api:
    from: ${PHONE_NUM}
    key: ${COOLSMS_API_KEY}
    secret: ${COOLSMS_SECRET_KEY}


jwt:
  token:
    secret: ${JWT_SECRET_KEY}
    header: ${JWT_RESOLVE_HEADER}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error


server:
  port: 8081