spring:
  profiles:
    include:
      - mysql
      - secret
      - aws

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error